//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPToolkit.Resources.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res_en_us {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res_en_us() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERPToolkit.Resources.Lang.res_en_us", typeof(res_en_us).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aditional Information.
        /// </summary>
        internal static string aditionalInfo {
            get {
                return ResourceManager.GetString("aditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artwork by.
        /// </summary>
        internal static string artworkBy {
            get {
                return ResourceManager.GetString("artworkBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinícius M. Freitas.
        /// </summary>
        internal static string artworkByValue {
            get {
                return ResourceManager.GetString("artworkByValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documented by.
        /// </summary>
        internal static string documentedBy {
            get {
                return ResourceManager.GetString("documentedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinícius M. Freitas.
        /// </summary>
        internal static string documentedByValue {
            get {
                return ResourceManager.GetString("documentedByValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent! The exception will be analyzed as soon as possible.
        /// </summary>
        internal static string emailSent {
            get {
                return ResourceManager.GetString("emailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERPToolkit.dll - The ERP Toolkit
        ///Copyright (C) 2014  Vinícius M. Freitas
        ///
        ///This program is free software; you can redistribute it and/or
        ///modify it under the terms of the GNU General Public License
        ///as published by the Free Software Foundation; either version 2
        ///of the License, or (at your option) any later version.
        ///
        ///This program is distributed in the hope that it will be useful,
        ///but WITHOUT ANY WARRANTY; without even the implied warranty of
        ///MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string erptoolkit_license {
            get {
                return ResourceManager.GetString("erptoolkit_license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string exception {
            get {
                return ResourceManager.GetString("exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception From.
        /// </summary>
        internal static string exceptionFrom {
            get {
                return ResourceManager.GetString("exceptionFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Message.
        /// </summary>
        internal static string exceptionMessage {
            get {
                return ResourceManager.GetString("exceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Type.
        /// </summary>
        internal static string exceptionType {
            get {
                return ResourceManager.GetString("exceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string license {
            get {
                return ResourceManager.GetString("license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send e-mail.
        /// </summary>
        internal static string sendEmail {
            get {
                return ResourceManager.GetString("sendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking &apos;Send&apos;, automatically send to the developer the exception, causing rapid resolution..
        /// </summary>
        internal static string sendEmailInfo {
            get {
                return ResourceManager.GetString("sendEmailInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to.
        /// </summary>
        internal static string sendTo {
            get {
                return ResourceManager.GetString("sendTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter.
        /// </summary>
        internal static string unknownParameter {
            get {
                return ResourceManager.GetString("unknownParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel ?.
        /// </summary>
        internal static string wantToCancel {
            get {
                return ResourceManager.GetString("wantToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Written by.
        /// </summary>
        internal static string writtenBy {
            get {
                return ResourceManager.GetString("writtenBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinícius M. Freitas.
        /// </summary>
        internal static string writtenByValue {
            get {
                return ResourceManager.GetString("writtenByValue", resourceCulture);
            }
        }
    }
}
